FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o client ./cmd/client/main.go

FROM scratch as runtime

COPY --from=builder /app/client /client

CMD ["/client"]
